import React, { useMemo } from 'react';
import { useTheme } from 'next-themes';
import Link from 'next/link';
import Image from 'next/image';
import { Carousel } from 'react-responsive-carousel';
import Layout from '@/components/Layout';
import Head from 'next/head';
import AnimatedText from '@/components/AnimatedText';
import { LinkArrow } from '@/components/Icons';
import TransitionEffects from '@/components/TransitionEffects';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import profilePic from '../../public/images/profile/pic1.jpeg';
import bgimg from '../../public/images/profile/background.jpeg';
import { FaGithub, FaFacebook, FaInstagram, FaLinkedin } from 'react-icons/fa';

// Import your personal images
import personalImage1 from "../../public/images/profile/pic2.jpeg";
import personalImage2 from "../../public/images/profile/pic3.jpeg";
import personalImage3 from "../../public/images/profile/pic4.jpeg";
import personalImage4 from "../../public/images/profile/pic5.jpeg";

export default function Home() {
  const { theme } = useTheme();

  // Update the images array with your personal images
  const images = useMemo(() => [
    personalImage1,
    personalImage2,
    personalImage3,
    personalImage4,
  ], []);

  return (
    <>
      <Head>
        <title>Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffects />
      <main className={`flex items-center text-${theme === 'dark' ? 'dc1' : 'dark'} w-full min-h-screen dark:text-dc1`}>
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="w-full h-screen relative">
            <Image
              src={bgimg}
              className="absolute inset-0 w-full h-full object-cover z-10"
              priority
              alt="Background Image"
            />
            <div className="absolute inset-0 flex items-center justify-center z-20">
              <div className="max-w-3xl px-6 text-center">
                <h1 className="font-bold text-5xl md:text-4xl sm:text-3xl">
                  <AnimatedText
                    text="Turning Vision Into Reality With Coding And Designing."
                    className="!text-7xl lg:!text-5xl sm:!text-3xl text-light"
                  />
                </h1>
                <AnimatedText
                  text=" As a skilled Front-end developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles, showcasing my expertise in React.js and web development."
                  className="text-light mt-4 text-xl md:text-lg sm:text-base"
                />
              </div>
            </div>
          </div>
          <br></br>
          <div className="flex items-center justify-between w-full h-screen lg:flex-col lg:pt-8">
            <div className="w-full lg:w-2/3 flex items-start lg:text-center lg:items-center lg:justify-center">
              <div className="text-left lg:text-center">
                <h1 className="text-4xl lg:text-5xl xl:text-6xl font-bold mb-4">
                  Hello, My name is Yuvraj Singh
                </h1>
                <h1 className="text-4xl lg:text-5xl xl:text-6xl font-bold mb-4">
                  I am a Student, Developer & Designer.
                </h1>
                <p className="text-lg font-semibold leading-relaxed lg:leading-normal lg:text-base sm:text-sm">
                  Experienced application programmer analyst and technical associate with expertise in managing teams, leading projects, and addressing technical challenges. Committed to continuous self-development and staying updated with emerging technologies. Goal-driven professional aiming to leverage skills in application programming, data analysis, and leadership to drive successful outcomes and foster innovation.
                </p>
                <div className="flex items-center mt-4 lg:self-center flex-wrap">
                  <Link
                    href="/Resume.pdf"
                    target="_blank"
                    className="flex items-center bg-dark text-light p-2.5 px-6 mr-2 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-dc1 dark:text-dark hover:dark:bg-dark hover:dark:text-dc1 hover:dark:border-dc1 md:p-2 md:px-4 md:text-base sm:p-0.5 mb-2"
                    download={true}
                  >
                    Resume <LinkArrow className="w-6 m-1" />
                  </Link>
                  <Link
                    href="mailto:syuvraj1900@gmail.com"
                    target="_blank"
                    className="flex items-center bg-dark text-light p-2.5 px-6 mr-2 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-dc1 dark:text-dark hover:dark:bg-dark hover:dark:text-dc1 hover:dark:border-dc1 md:p-2 md:px-4 md:text-base sm:p-0.5 mb-2"
                  >
                    Contact <LinkArrow className="w-6 m-1" />
                  </Link>
                  <Link
                    href="https://github.com/syuvraj19"
                    target="_blank"
                    className="flex items-center bg-dark text-light p-2.5 px-6 mr-2 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-dc1 dark:text-dark hover:dark:bg-dark hover:dark:text-dc1 hover:dark:border-dc1 md:p-2 md:px-4 md:text-base sm:p-0.5 mb-2"
                  >
                    <FaGithub className="w-6 h-6 m-1" />
                  </Link>
                  <Link
                    href="https://www.facebook.com/profile.php?id=100011399805579"
                    target="_blank"
                    className="flex items-center bg-dark text-light p-2.5 px-6 mr-2 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-dc1 dark:text-dark hover:dark:bg-dark hover:dark:text-dc1 hover:dark:border-dc1 md:p-2 md:px-4 md:text-base sm:p-0.5 mb-2"
                  >
                    <FaFacebook className="w-6 h-6 m-1" />
                  </Link>
                  <Link
                    href="https://instagram.com/yuvrxj.17"
                    target="_blank"
                    className="flex items-center bg-dark text-light p-2.5 px-6 mr-2 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-dc1 dark:text-dark hover:dark:bg-dark hover:dark:text-dc1 hover:dark:border-dc1 md:p-2 md:px-4 md:text-base sm:p-0.5 mb-2"
                  >
                    <FaInstagram className="w-6 h-6 m-1" />
                  </Link>
                  <Link
                    href="https://www.linkedin.com/in/yuvraj-singh-s29/"
                    target="_blank"
                    className="flex items-center bg-dark text-light p-2.5 px-6 mr-2 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-dc1 dark:text-dark hover:dark:bg-dark hover:dark:text-dc1 hover:dark:border-dc1 md:p-2 md:px-4 md:text-base sm:p-0.5 mb-2"
                  >
                    <FaLinkedin className="w-6 h-6 m-1" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="w-full lg:w-1/3 flex justify-center mt-8 lg:mt-0">
              <Carousel
                showThumbs={false}
                infiniteLoop={true}
                autoPlay={true}
                interval={4000}
                stopOnHover={true}
                swipeable={true}
                transitionTime={500}
                className="w-full"
              >
                {images.map((image, index) => (
                  <div key={index} className="carousel-item">
                    <Image src={image} alt={`Image ${index + 1}`} className="w-full h-auto" />
                  </div>
                ))}
              </Carousel>
            </div>
          </div>
        </Layout>
      </main>
      <hr className="absolute-t border border-dark dark:border-dc1 w-full" />
    </>
  );
}
